In [1]:
my_list = [1,2,3]


In [2]:
my_list
import numpy as np

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((4,5))  #rows by columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones(3) #same as zeros but of 1

array([1., 1., 1.])

In [10]:
np.linspace(0,5,10) #gives enevly distributed numbers between 2 digits

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [11]:
#identity matrix

np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.random.rand(5) #random numbers between 0 and 1 in 1D 

array([0.55543673, 0.99169673, 0.0355895 , 0.11586124, 0.5490164 ])

In [13]:
np.random.rand(5,5) #random numbers between 0 and 1 in 2D

array([[4.00653685e-01, 3.40805409e-01, 4.48000666e-01, 6.21653070e-02,
        2.27953786e-01],
       [1.02261799e-01, 8.56621150e-04, 2.13311021e-01, 4.81044842e-01,
        6.43134223e-02],
       [9.61587977e-02, 9.31154231e-01, 4.84433520e-01, 8.23783288e-03,
        4.58267449e-01],
       [5.31403891e-01, 3.30987649e-01, 5.91816319e-01, 8.83771500e-01,
        4.60119109e-01],
       [2.64213477e-01, 6.38192754e-01, 1.21927149e-01, 4.33688349e-01,
        7.07719758e-01]])

In [14]:
np.random.randn(4,4) #random numbers around 0

array([[ 1.04925166, -0.20147233, -2.04758315,  1.39635019],
       [-0.52494534,  0.58545622,  1.7793245 ,  0.20836908],
       [ 0.07656042,  0.48580899,  0.0679285 ,  1.05684538],
       [ 0.19513884,  0.72798054, -0.11318217,  0.60996421]])

In [15]:
np.random.randint(1,100,20) #random integer between 2 numbers

array([57, 68, 93, 48,  3, 53, 55, 76, 64, 18, 79, 16, 65, 32, 13,  7,  3,
       63, 24, 42])

In [16]:
arr= np.arange(25)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
randarr = np.random.randint(0,50,10)

In [19]:
randarr

array([ 2, 27, 43, 18, 33, 40,  8, 43, 26, 29])

In [20]:
arr.reshape(5,5) #exact numbers 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
np.max(arr)

24

In [22]:
np.min(randarr)

2

In [23]:
randarr


array([ 2, 27, 43, 18, 33, 40,  8, 43, 26, 29])

In [24]:
randarr.argmax()

2

In [25]:
randarr.argmin()

0

In [26]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [27]:
arr.dtype

dtype('int32')